### ISSUE TITLE
Add section on provider panel attribution

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/knowledge_base#159]

**Comment by chase-jones** [comment]
@aneiderhiser , can you elaborate more on what is meant by provider attribution? Is this specific to a CMMI program's attribution methodology, or more so in general how one would go about attributing patients to providers? Or something else entirely?

**Comment by aneiderhiser** [comment]
@chase-jones my thought is we add a new top-level section called "Provider Attribution".  CMMI methodology is a great place to start.  I also think a general overview would be good.  And more advanced would be comparing methods e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6549236/

**Comment by chase-jones** [comment]
I'll take a swing at this next @aneiderhiser
