### ISSUE TITLE
Improve the section on CMS-HCC risk adjustment

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/knowledge_base#163]
Explain the methodology in detail using examples, so that someone can read this and completely understand how it works.  Use flow chart diagrams to illustrate clearly.

**Comment by chase-jones** [comment]
@aneiderhiser , how to calculate risk on an individual patient, or how the risk model is developed?

**Comment by aneiderhiser** [comment]
@chase-jones was thinking a detailed walkthrough on an individual (or maybe a couple of different examples).  Goal would be to help someone completely understand the inputs and how risk scores are ultimately calculated.

**Comment by aneiderhiser** [comment]
FWIW I think a flow chart diagram goes an a long way in explaining this type of methodology.

**Comment by chase-jones** [comment]
Okay, I'll take a swing at this!
